### ISSUE TITLE
Create a GitHub Pages associated web page

### ISSUE THREAD

**Issue by alexanderpanchenko** [skoltech-nlp/inappropriate-sensitive-topics#4]
Create the Github pages to generate a similar web site (on the basis of the completed README file)
https://skoltech-nlp.github.io/coqas/

**Comment by alexanderpanchenko** [comment]
I added 'Admin' rights to you. Go to Settings page and you will see the options to create Github pages.

**Comment by bbkjunior** [comment]
нужно мерджить ветку Pages в мэин ветку?

**Comment by bbkjunior** [comment]
https://skoltech-nlp.github.io/inappropriate-sensitive-topics/
